name: Build correct docker containers

on:
  workflow_dispatch:
    user:
      - benchungiscool

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ensure k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

      - name: Ensure k8s
        env:
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          sshpass -p $SUDO_PASSWORD ssh user@your-server "kubectl get pods"

      - name: Add
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo 'FROM python:bookworm
            WORKDIR /app
            COPY requirements.txt /app/requirements.txt
            COPY src /app/
            RUN pip install --no-cache-dir -r requirements.txt
            CMD ["python", "-m", "server"]' > ~/kube_learning/docker/server_Dockerfile
            echo 'FROM python:bookworm
            WORKDIR /app
            COPY requirements.txt /app/requirements.txt
            COPY src /app/
            RUN pip install --no-cache-dir -r requirements.txt
            CMD ["python", "-m", "client"]' > ~/kube_learning/docker/client_Dockerfile

      - name: Build docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning
            docker-compose build
            docker push benchungbenchung/k8s_test:server001
            docker push benchungbenchung/k8s_test:client001
