name: Build correct docker containers

on:
  workflow_dispatch:
    user:
      - benchungiscool

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ensure k8s
        run: sshpass -p ${{ secrets.SUDO_PASSWORD }} ssh user@your-server "kubectl get pods"

      - name: Shuffle dockerfiles
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning/docker
            mv client_Dockerfile correct_client_Dockerfile
            mv server_Dockerfile correct_server_Dockerfile
            mv wrong_client_Dockerfile client_Dockerfile
            mv wrong_server_Dockerfile server_Dockerfile

      - name: Build docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/kube_learning
            docker-compose build
            docker push benchungbenchung/k8s_test:server001
            docker push benchungbenchung/k8s_test:client001
